# Sublime Text (Mac)
if [ -f "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" ]; then
  alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
fi

alias be="bundle exec"
alias reload="source $HOME/.bash_profile"
